//
// Created by chema on 3/13/19.
//

#ifndef MATRIX_MARKET_SUITE_CONJUGATEGRADIENTSOLVERBASIC_CUDA_H
#define MATRIX_MARKET_SUITE_CONJUGATEGRADIENTSOLVERBASIC_CUDA_H

#endif //MATRIX_MARKET_SUITE_CONJUGATEGRADIENTSOLVERBASIC_CUDA_H
